version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./docker/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8989:80
    container_name: app-nginx
    depends_on:
      - php
    networks:
      - nginx_net

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # image: php:8.1-fpm
    volumes:
      - ./src:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    container_name: app-php
    environment:
      - PHP_IDE_CONFIG=serverName=ideServer
    depends_on:
      - db
    networks:
      - nginx_net

  db:
    image: mariadb
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_db
      MYSQL_PASSWORD: db-pass
    ports:
      - 3305:3306
    # command: mysqld --character-set-server=utf8 --collation-server=utf8mb4_unicode_ci
    container_name: app-maria
    networks:
      - nginx_net

networks:
  nginx_net:
    driver: bridge
    name: nginx_net
